import React from 'react';
import { Copy, CheckCircle } from 'lucide-react';
import Layout from '../components/Layout';

export default function SetupInstructions() {
  const sqlScript = `
-- 1. Create Enum Types for dropdowns
create type service_category as enum ('Web Development', 'App Development', 'Business Automation');
create type lead_status as enum ('New Lead', 'Follow-up Pending', 'Contacted', 'Converted', 'Not Interested');

-- 2. Create Customers Table
create table customers (
  id bigint generated by default as identity primary key,
  business_name text not null,
  contact_number text not null,
  location text,
  service_category service_category not null,
  follow_up_date date not null,
  follow_up_time time not null,
  notes text,
  status lead_status default 'New Lead',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security
alter table customers enable row level security;

-- 4. Create Policy (Allow public access for this demo)
-- Note: In a production app with auth, you would change "true" to "auth.uid() = user_id"
create policy "Enable all access for all users" on customers for all using (true) with check (true);
`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(sqlScript);
    alert('SQL script copied to clipboard!');
  };

  return (
    <Layout>
      <div className="p-2">
        <div className="flex items-center gap-2 mb-4">
          <div className="bg-green-100 p-2 rounded-full text-green-600">
            <CheckCircle size={24} />
          </div>
          <h1 className="text-2xl font-bold text-slate-900">App Connected!</h1>
        </div>
        
        <div className="space-y-6">
          <section className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
            <h2 className="font-bold text-lg text-indigo-600 mb-2">Final Step: Create Database Table</h2>
            <p className="text-slate-600 text-sm mb-4">
              The app is now connected to your Supabase project (<strong>vsmmwrukydbcvzgwziiy</strong>).
              <br />
              To finish setup, run this SQL script in your Supabase SQL Editor to create the necessary table.
            </p>
            
            <div className="relative bg-slate-900 rounded-xl p-4 overflow-x-auto">
              <button 
                onClick={copyToClipboard}
                className="absolute top-2 right-2 bg-slate-700 text-white p-2 rounded-lg hover:bg-slate-600 transition-colors"
                title="Copy to clipboard"
              >
                <Copy size={16} />
              </button>
              <pre className="text-xs text-green-400 font-mono leading-relaxed">
                {sqlScript}
              </pre>
            </div>
          </section>

          <div className="text-center">
             <a 
               href="https://supabase.com/dashboard/project/vsmmwrukydbcvzgwziiy/sql/new" 
               target="_blank" 
               rel="noreferrer"
               className="inline-flex items-center justify-center bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-6 rounded-xl transition-colors"
             >
               Open Supabase SQL Editor
             </a>
          </div>
        </div>
      </div>
    </Layout>
  );
}
